title : Satya Sai Vamshi Krishna Arza
logo : /images/my photo.jpg
location : Chicago, Illinois
email : arzavamshikrishna@gmail.com
github : vamshi-arza
linkedin : https://www.linkedin.com/in/satya-sai-vamshi-krishna-arza-780b90b8/
theme : jekyll-theme-minimal
